### ISSUE TITLE
Could not repeat the code in the arXiv:2305.11354 paper.

### ISSUE THREAD

**Issue by LePingKYXK** [r2stanton/pyrovskite#1]
Hi, I am very excited to read the paper from arXiv and then tried this package. However, I could not repeat the example in your paper (on page 4) as follows.

```python
from pyrovskite.builder import make_2drp
A = "./methylammonium.xyz"
Ap = "./butylammonium.xyz"
org_A_2drp = make_2drp (Ap , A, "Pb", "I", 2, 3)
in_A_2drp = make_2drp (Ap , "Cs", "Pb", "I", 2, 3)
```

I was in the directory of `/public/home/clxy_wh/BACKUP/pyrovskite/tests/data` .  

There are many `.cif` and `.xyz` files, shown below.
```bash
(pyrovskite) [clxy_wh@login data]$ ls
3AMP_CsInSbI_dj.cif  mapbi3_2x2x2.cif   methylammonium.xyz     test_bulk.json    test_mono.json         testvcopt_fcopt.cif  testvcopt_vcopt.inp
benzylammonium.xyz   mapbi3.cif         test_2ddouble_dj.json  test_dj.json      test_perovskite_1.cif  testvcopt_fcopt.py
mapbi_2d_diag.cif    mapbi_3d_diag.cif  test_2ddouble_rp.json  test_double.json  test_rp.json           testvcopt_vcopt.cif
```
I can find the `methylammonium.xyz` file as demonstrated in the paper, but there is only `benzylammonium.xyz` instead of `butylammonium.xyz`. 

The codes below were what I tried. (I installed the Pyrovskite package in the virtual environment via Anaconda 3).

```bash
(pyrovskite) [clxy_wh@login data]$ python
Python 3.10.11 (main, Apr 20 2023, 19:02:41) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyrovskite.builder import make_2drp
>>>
>>> Ap = "./benzylammonium.xyz"
>>> in_A_2drp = make_2drp(Ap, "Cs", "Pb", "I", 2, 3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/public/home/clxy_wh/BACKUP/pyrovskite/pyrovskite/builder.py", line 278, in make_2drp
    raise ValueError("Ap must be a molecule in the form of an Atoms "
ValueError: Ap must be a molecule in the form of an Atoms object, not a single atom as a string.
>>> 
```

I also tried to use the `methylammonium.xyz` as Ap, however, the same ValueError appeared. 
Could you please kindly help me to fix it? Thanks a lot.

**Comment by LePingKYXK** [comment]
I found the solution in the Jupyter Notebook file (`The_builder_module.ipynb` in the `example` directory).

First of all, I need to use `ase.io.read()` function to load the `.xyz` file. 

```python
>>> import ase
>>> 
>>> Ap = ase.io.read("./methylammonium.xyz")
>>> 
>>> in_A_2drp = make_2drp(Ap, "Cs", "Pb", "I", 2, 3)
>>> in_A_2drp.write("AAAA.cif")
```

It works now!

I have an additional question. I understand the second to last parameter of “2” means two layers, but I am not sure **what's the meaning of the last parameter "3" stand for**?  The comments in `In [5]` showed that it is "2*BX-bond length", while in `In [6]` it is presented as "BX-bond length", which makes me confused....

**Comment by r2stanton** [comment]
First off thanks very much for using the code! I'm glad the A, Ap issue got sorted out, maybe I should add the ability to simply pass those filenames as strings and have the code open up the structure files automatically if it sees they're not passed as Atoms objects. That would make the first example you sent would work out as is, and it may be nice to have both methods available.

As for the ```make_X``` functions, yes the last parameter in those is the BX-bond distance. It used to be BX*2 in previous versions of the code, but before publishing the package I just changed everything to BX-bond distances, removing the factor of 2 to make it more intuitive. I thought I caught all of the spots I mentioned it in the examples but I missed the one you pointed out, so I'll update that shortly.

Also shortly I'll be adding a bunch of organic A' and A site cations to a res directory of some sort in the repo so that should make it less of a hassle having to track those down in the folder for the test data. Thanks again!

**Comment by LePingKYXK** [comment]
> First off thanks very much for using the code! I'm glad the A, Ap issue got sorted out, maybe I should add the ability to simply pass those filenames as strings and have the code open up the structure files automatically if it sees they're not passed as Atoms objects. That would make the first example you sent would work out as is, and it may be nice to have both methods available.
> 
> As for the `make_X` functions, yes the last parameter in those is the BX-bond distance. It used to be BX*2 in previous versions of the code, but before publishing the package I just changed everything to BX-bond distances, removing the factor of 2 to make it more intuitive. I thought I caught all of the spots I mentioned it in the examples but I missed the one you pointed out, so I'll update that shortly.
> 
> Also shortly I'll be adding a bunch of organic A' and A site cations to a res directory of some sort in the repo so that should make it less of a hassle having to track those down in the folder for the test data. Thanks again!

Thank you for your quick response! 
I think you do not need to modify the A, Ap issue in the current code (to avoid introducing bugs), just modifying the paper is enough. 

Hoping for new features.  :)
