### ISSUE TITLE
Feature requirement

### ISSUE THREAD

**Issue by LePingKYXK** [r2stanton/pyrovskite#2]
Hi Robert,
I found that the structures generated by `pyrovskite` are (0,0)  positions with the interlayer octahedrons top-to-top stacked. Is it possible to generate the (0, 1/2) shift between the octahedron interlayers, as shown in panels (b) and (d) of the figure below?

![image](https://github.com/r2stanton/pyrovskite/assets/14786161/ef71d8d4-bd25-448d-9fa7-1754bb1a57b9)

**Comment by r2stanton** [comment]
Hi just to be sure we're talking about the same thing, is what you're referring to here pretty much the same as the "Alternating Cation (ACI) Phase"? (circled in blue below, this is Figure 1 from https://doi.org/10.1038/s41565-020-00811-1)

I have played a bit with adding these phases, but they're not currently in the codebase. One thing that has held up the implementation is that ACI phases in the literature (the paper you've shown above is a good example) consist of both DJ and RP phases where adjacent layers sometimes share, and sometimes don't share a spacer. So the implementation for those shifts in adjacent layers gets a bit more involved and dependent on the "base" phase so to speak.

There's a bit of a quick fix that can be done which hopefully will be able to work for your systems. It requires some playing with the numbers depending on the system, and checking that it doesn't result in overlapping atoms (tends to happen for many spacers in the DJ ACI phase unfortunately, this is the primary reason it's not in the code yet). Either way though, I've been able to use something like this to get ACI phases, so hopefully it can work for you as well for now before I can properly implement in the code:

```python
perov = make_2drp(...)

translate_list = []
spacer_z_height =# Just below the lowest z-coordinate of spacers you want shifted
BX_z_height = # Just below the lowest z-coordinate of BX atoms you want shifted 

BX_list = ["Pb", "I"] # List of your B, X components.
spacer_list = ["C", "H", "N", "O"] # List of species in spacers

# Select the atoms by type above some certain height for the shift.
for atom in perov:
    if atom.symbol in spacer_list and atom.position[2] > spacer_z_height:
        translate_list.append(atom.index)
    if atom.symbol in BX_list and atom.positions > BX_z_height:
        translate_list.append(atom_index)
        
# Then loop over and translate the atoms in translate_list by the desired amount.
# This is the main tricky part to get right while avoiding atoms colliding.
```



![image](https://github.com/r2stanton/pyrovskite/assets/38013946/af6f4d8d-8deb-44b0-8eef-7c331b444861)

**Comment by r2stanton** [comment]
Closing for now, trying to overhaul some things within the builder module before adding the ACI phase to aid in dealing with spacers/organic cations with abnormal geometries.

**Comment by r2stanton** [comment]
Closing for now, trying to overhaul some things within the builder module before adding the ACI phase to aid in dealing with spacers/organic cations with abnormal geometries.
